### ISSUE TITLE
Add Data.Sequence and Data.Tree support

### ISSUE THREAD

**Issue by viercc** [haskellari/functor-classes-compat#8]
Hi,

Out of necessity, I made a [similar package](https://github.com/viercc/base-containers-orphans) (only on GitHub) without knowing this package exists.
Since I discovered this, I want to migrate to this package rather than using my cheaply built package. But to do it, I need two additions to this package.

* Instances of `Data.Sequence.Seq`
* Instances of `Data.Tree.Tree`

Could you consider adding them?

**Comment by phadej** [comment]
I'll be happy to add more instances. Please make a PR.
